### ISSUE TITLE
youtube-dl URL to mp3 -> mp3: only layer3 (want 1; got 3) is supported

### ISSUE THREAD

**Issue by aaronleopold** [faiface/beep#117]
I am learning go and creating a small program to fetch audio urls (via youtube-dl) and feed them into beep to play. I'm currently alternating between two errors: 

1. `mp3: mp3: only MPEG version 1 (want 3; got 0) is supported`
2. `mp3: mp3: only layer3 (want 1; got 3) is supported`

I get the former error from the resulting url of `youtube-dl -i --get-url --extract-audio --audio-format mp3 'https://www.youtube.com/watch?v=fkM3nSz_qjc'`
The URL returned will expire sometime soon I believe, but I will link it [here](https://r5---sn-5ualdnee.googlevideo.com/videoplayback?expire=1617329466&ei=2ihmYMeIBs-gj-8P3reeiAk&ip=2600%3A8807%3Ac040%3A3740%3Af8f1%3A3b64%3Aab35%3A256c&id=o-AMNrcCXuBcXkQ02b_jNUUwBry-76VqV6kHJC8NcwlzE9&itag=251&source=youtube&requiressl=yes&mh=eW&mm=31%2C26&mn=sn-5ualdnee%2Csn-p5qs7n76&ms=au%2Conr&mv=m&mvi=5&pl=35&initcwndbps=1718750&vprv=1&mime=audio%2Fwebm&ns=PgUN76l1Tkvad7M3oyU_9RAF&gir=yes&clen=2522357&otfp=1&dur=154.041&lmt=1586537913037241&mt=1617307486&fvip=5&keepalive=yes&fexp=24001373%2C24007246&c=WEB&txp=6211222&n=GH1QHk8x--SunIV5-&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cotfp%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgSFTsnfUBibv1litFQtJX9bowwKYt37IekPJgq0qxDbQCIQDR6TaZIr0jFRzx0W1kUKANMQ8c6CLPT5UBFcWjV0eRYg%3D%3D&sig=AOq0QJ8wRAIgXu3nCE3jCIeA9f1onC8JirrYkmDNLcskYY16zTnNcm0CIH82JE0hpFTmzwC5s0iuxhn7Y2kaKT-BCCQIFYwQ4Z6f)

I get the latter error from the resulting url of `youtube-dl -i --get-url --extract-audio -f 140  --audio-format mp3 'https://www.youtube.com/watch?v=fkM3nSz_qjc'`
The URL returned will expire sometime soon I believe, but I will link it [here](https://r5---sn-5uaeznkl.googlevideo.com/videoplayback?expire=1617328653&ei=rSVmYIqIJoeckAOkxq-wAw&ip=2600%3A8807%3Ac040%3A3740%3Af8f1%3A3b64%3Aab35%3A256c&id=o-AEhCRv6mm5I8MA27hWVzYSaxRxmYP9HA3G_9TeCdBBfO&itag=140&source=youtube&requiressl=yes&mh=eW&mm=31%2C26&mn=sn-5uaeznkl%2Csn-p5qlsnzd&ms=au%2Conr&mv=m&mvi=5&pl=35&initcwndbps=1787500&vprv=1&mime=audio%2Fmp4&ns=nAW6wZu_JSEolBjVKxvwZesF&gir=yes&clen=2494465&otfp=1&dur=154.087&lmt=1586537917282900&mt=1617306767&fvip=5&keepalive=yes&fexp=24001373%2C24007246&c=WEB&txp=6211222&n=fxzrfNzMsuk_i03yi&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cotfp%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAK4J2kQrHPF5qLQ7YTWK1yzBXgxKUO62PyMVcXqhsKxsAiBfxBPRxHJyxNQIpGuL7WXWZbxVwRyaCDG6-cdtaAojJA%3D%3D&sig=AOq0QJ8wRQIgVv4HxEb6RKhf58rFTi4K9ZCGtATXLrBEgda1VAY_N1YCIQDcgnj4XaBQ7O-NejshkoPNjxkyjPdFm6oEcNfz8vSgaQ==)

```go
func getTestUrl() string {
	youtubeDl, err := exec.LookPath("youtube-dl")
	if err != nil {
		log.Fatalf("youtube-dl installation could not be found")
	}

	ydl := exec.Command(
		youtubeDl, 
		"--get-url", 
		"--extract-audio", 
		"--audio-format", 
		"mp3", 
		"https://www.youtube.com/watch?v=fkM3nSz_qjc",
	)

	link, err := ydl.Output()
	if err != nil {
		report(err)
	}

	return strings.TrimSpace(string(link))
}

func TestPlay() {
	resp, err := http.Get(getTestUrl())
	if err != nil {
		log.Fatalln(err)
	} else {
	        // looks something like --> &{0xc000224180 {0 0} false <nil> 0x427ada0 0x427ad20}
		fmt.Println(resp.Body)
	}

	streamer, format, err := mp3.Decode(resp.Body)
	if err != nil {
		report(err)
	}

	defer streamer.Close()

	speaker.Init(format.SampleRate, format.SampleRate.N(time.Second/10))
	speaker.Play(streamer)

	select {}
}
```

Additionally, I downloaded the second mp3 and attempted to load it locally with the same error:

```go
func TestLocalPlay() {
	f,err := os.Open("test.mp3")

	fmt.Println(f) // &{0xc000068840}

	streamer, format, err := mp3.Decode(f)
	if err != nil {
		log.Fatal(err) // --> mp3: mp3: only layer3 (want 1; got 3) is supported
	}
	defer streamer.Close()

	speaker.Init(format.SampleRate, format.SampleRate.N(time.Second/10))
        speaker.Play(streamer)
}
```

**Comment by MarkKremer** [comment]
Hey, I didn't download the files in time so I couldn't test. Could you try it with the master branch of beep?
```bash
go get -u github.com/faiface/beep@master
```

It uses some newer dependencies. It just doesn't have a tag yet so it doesn't download it by default.

**Comment by aaronleopold** [comment]
Hey Mark, thanks for replying! I just updated and got a different error:

```bash
&{0xc0001ac180 {0 0} false <nil> 0x427ae40 0x427adc0} # --> the resp.Body
mp3: mp3: MPEG version 2.5 is not supported # --> the different error
exit status 1
```

I also updated my original comment just to give a little more code context for how I'm obtaining the URL's

**Comment by MarkKremer** [comment]
I think this is a bit difficult to fix on beep's end. The library that we use (`github.com/hajimehoshi/go-mp3`) doesn't support it. So either they need to implement this, which I think is not easy, or we need to use another library which does support it, which I'm not sure exists.

Beep supports some other formats besides mp3, and so does youtube-dl. I tried some other combinations but no luck. All formats gave me some kind of error. Although I didn't look far into why. I think your best bet is to convert the audio from youtube to a format that beep does support. youtube-dl may have some options using avconf or ffmpeg to do this for you. Or you could use avconf/ffmpeg yourself if that is not the case.

**Comment by aaronleopold** [comment]
Okay, thanks for your help Mark! Since this is more of an issue with the `go-mp3` dependency I can go ahead and just close this issue if that's your preference? I'll try and use some other formats as you suggested, and maybe spend time looking into some of the other post-processing options youtube-dl has (I know they use ffmpeg as the default).

**Comment by MarkKremer** [comment]
Close it :+1: Feel free to reopen or create a new issue if you have more questions.
