### ISSUE TITLE
Change speed without affecting pitch

### ISSUE THREAD

**Issue by baldore** [faiface/beep#122]
Hello! Thanks for the great work on this library.

Quick question: is it possible to change the speed without affecting the pitch? I'm trying the Speedy player example, but not sure if there's a way to not affect the pitch.

Thanks in advance.

**Comment by gilwo** [comment]
check this repo: https://github.com/Muges/go-tsm
it appear that someone already delved into this issue and it was implemented using beep streamer. 🎉 😄 
I am not sure how to achieve the functionality for Realtime audio stream but its a start
