### ISSUE TITLE
Small static noise is played every time a .wav sample is looped

### ISSUE THREAD

**Issue by kharland** [faiface/beep#14]
os: mac OSX
go: 1.9.2 darwin/amd64

When looping a sound, each new loop begins with a tiny but noticeable static noise.  To repro:

```go
// init speaker, load sound... etc.
speaker.Play(beep.Loop(-1, sound))
```
For reference, the audio file I'm looping is here: https://drive.google.com/open?id=1xucV3r61huoVKA5NALsJs4k44-WwDEl6

**Comment by faiface** [comment]
Hi, thanks for reporting! Sorry I only respond now, there really was a bug, the WAV decoder streamed past the end of audio data if there were some bytes after the data section. That's fixed now, so it only streams as much as it should. It was a little tricky one to find, so thanks for reporting!

Tell me if it fixed it on your side, and if so, we can close this issue.

**Comment by kharland** [comment]
That did it! Thanks for fixing this.
