### ISSUE TITLE
Option not to close `io.Reader` in decoders

### ISSUE THREAD

**Issue by samhocevar** [faiface/beep#147]
Decoders such as `wav.Decode` make sure the provided `io.Reader` is closed when an error occurs or when the returned streamer is closed. In my case I want to keep the file descriptor because I use `wav.Decode` to read WAV files stored inside a binary container.

For now my workaround is to hide the `io.Closer` implementation of my `os.File`:

```golang
type PureReader struct {
        r io.Reader
}

func (pr *PureReader) Read(buf []byte) (int, error) {
        return pr.r.Read(buf)
}

[...]

    s, fmt, err := wav.Decode(&PureReader{r: f})
```

Do you believe Beep could provide a more convenient way to do this?

**Comment by laustbn** [comment]
Go's standard library already provides `io.NopCloser()` for this purpose. You should be able to do:

`s, fmt, err := wav.Decode(io.NopCloser(f))`.

See https://pkg.go.dev/io#NopCloser

**Comment by samhocevar** [comment]
Thanks, this works perfectly! Apologies, I should have researched the stdlib a bit more.
