### ISSUE TITLE
Some mp3 return SampleRate of 0 when decoding

### ISSUE THREAD

**Issue by zapic0** [faiface/beep#15]
I'm having an issue with some mp3, these files are decoded, no error is returned but format SampleRate has 0 value.

You can try to reproduce playing any mp3 from google text to speech, for instance:
http://translate.google.com/translate_tts?ie=UTF-8&client=tw-ob&q=testing%20for%20beep&tl=en

**Comment by Edwin-Luijten** [comment]
I am having the same issue, I attached the file I test with.
[audio_file.zip](https://github.com/faiface/beep/files/2183916/audio_file.zip)

I create attached file by base64 decode the response and store it as an .mp3 file.
When printing the sample rate, it show: 0.

**Comment by faiface** [comment]
This will probably be a problem with https://github.com/hajimehoshi/go-mp3, which is used by [beep/mp3](https://godoc.org/github.com/faiface/beep/mp3). @hajimehoshi

**Comment by hajimehoshi** [comment]
Huh, sorry but I'm quite busy to investigate those problems.

@faiface If you want to fix the problems asap, I'd recommend to consider to switch MP3 decoder to https://github.com/lieff/minimp3, which is well tested but not pure Go.
