### ISSUE TITLE
Tutorial Code Freezes if Called Twice

### ISSUE THREAD

**Issue by drgrib** [faiface/beep#157]
I am trying to create the simplest possible use of `beep` by creating a `Play` function that plays an MP3 using the tutorial code. I don't need any complex controllers or resampling. I just want to play the MP3. However when I call this code with a second MP3 (or the same MP3 a second time), the code freezes at the spot I have marked in the function.

How can I modify this code so that it doesn't freeze when called a second time? 

```
func Play(p string) error {
	f, err := os.Open(p)
	if err != nil {
		return errors.WithStack(err)
	}

	streamer, format, err := mp3.Decode(f)
	if err != nil {
		return errors.WithStack(err)
	}
	defer streamer.Close()

	err = speaker.Init(format.SampleRate, format.SampleRate.N(time.Second/10))
	if err != nil {
		return errors.WithStack(err)
	}

	done := make(chan bool)
	// Second call freezes HERE
	speaker.Play(beep.Seq(streamer, beep.Callback(func() {
		done <- true
	})))

	<-done
	return nil
}
```

**Comment by drgrib** [comment]
I had to create a global variable in the package to not call `speaker.Init`. It would be nice to have an example of the best way to implement a simple `play` function in the example code.

**Comment by able8** [comment]
Thanks. I also encountered this issue.  The second call to the speaker.Play() freezes.
