### ISSUE TITLE
Confused about initializing the speaker from a file

### ISSUE THREAD

**Issue by cheryllium** [faiface/beep#164]
In the tutorial, first we decode an mp3 file and then we used the `format` returned by the Decode function to call `Speaker.Init()`... But the tutorial also cautions not to call `Speaker.Init` every time we want to play something. 

Shouldn't we have to call it every time we want to play a new file, using the new `format` returned by decoding the new file? 

If not, is there a way I can initialize the speaker without having to decode a file first? For it seems neater if I can initialize the speaker first, then call a function to give it a song to play.

**Comment by MarkKremer** [comment]
The format given to `speaker.Init()` is used to interpret the samples pulled from the streamers given to `speaker.Play()`. These streamers must produce samples in a matching format to that what the speaker was initialized with.

Given a single audio file or multiple audio files with the same format, this is easy: configure the speaker using the format of the audio file. Just like you've done already.

If there are multiple audio files, and they have different formats then you need to choose what format you want to send to the speaker. For example `beep.Format{SampleRate: 44100, NumChannels: 2, Precision: 2}`. Then every `Streamer` you want to play must be converted to this format before you give it to `speaker.Play()`. This can be done by passing it through `beep.Resample(3, yourFormat.SampleRate, speakerFormat.SampleRate, yourMp3Streamer)`. Have a look at the function's docblock for a description of its arguments.

**Comment by cheryllium** [comment]
Thanks! That clears it up.
