### ISSUE TITLE
Out-of-bounds bug affecting faiface/beep and gopxl/beep

### ISSUE THREAD

**Issue by enn-msi** [faiface/beep#171]
Hi beep maintainers,

The company I work for utilizes the `gopxl/beep` package in one of our products, and we discovered an out-of-bounds read bug affecting both `gopxl/beep` and `faiface/beep`.

I would like to report this issue privately and follow responsible disclosure best practices, as it can pose a security vulnerability (Denial of Service) in scenarios where the functionality affected by the bug processes untrusted data. However, there is no `security.md` policy file in this repository, and I've got no reply to the emails I've sent to the maintainers/contributors (i.e., the ones I could find an email).

Could one of the project maintainers reach out to me or add the security.md policy file so I could report through Github, please?

Thanks

**Comment by dusk125** [comment]
@enn-msi please open this against gopxl/beep, this repository is no longer under development and is superseded by the gopxl fork.
As for reaching out directly to the maintainers, please join the gopxl discord and reach out there, we can setup a private channel there for the disclosure.
Thanks

**Comment by enn-msi** [comment]
Okay, thanks for the quick reply. I've opened the same issue on gopxl/beep.
