### ISSUE TITLE
How do i play the same file multiple times?

### ISSUE THREAD

**Issue by Snabel** [faiface/beep#19]
Hi, I cant figure out how to play the same sound effect multiple times, like every 5 seconds. Can you point me in the right direction?

**Comment by Snabel** [comment]
I see, thank you! (Close this issue)

**Comment by gonutz** [comment]
I was looking for this, only to find it while creating a new issue for it (Github pointed me to this one when I was typing in my keywords). Please consider adding this to your readme and as an example. I think this is of utmost importance as many people use your library alongside your pixel engine to create games and playing a certain sound effect in this way is the foremost use case for small WAV sound effects usually.

**Comment by faiface** [comment]
@gonutz You're right. I'll extend the README to a more fledged tutorial covering most features of Beep as soon as I can.

**Comment by gonutz** [comment]
Cool, thank you! :-)
