### ISSUE TITLE
packages not found

### ISSUE THREAD

**Issue by rafa-acioly** [faiface/beep#20]
After downloading `go get github.com/faiface/beep` and try to run a sample the follow errors appears:

```
# github.com/rafa-acioly/bitcoin-alert/vendor/github.com/hajimehoshi/oto
vendor/github.com/hajimehoshi/oto/player_linux.go:23:10: fatal error: alsa/asoundlib.h: No such file or directory
 #include <alsa/asoundlib.h>
          ^~~~~~~~~~~~~~~~~~
```

**Comment by faiface** [comment]
Sorry for not responding sooner. Beep uses Oto for the low-level playback implementation, so you need to install its prerequisites: https://github.com/hajimehoshi/oto#prerequisite
