### ISSUE TITLE
Add some Examples 

### ISSUE THREAD

**Issue by localleon** [faiface/beep#21]
Hello,

at the moment I enjoy your library very much. But a few examples would help a lot to get started quickly. Some Code Examples for the Mixer and basic .mp3/.wav playing

**Comment by faiface** [comment]
Sure. Right now I'm kinda busy, so if you, or anyone else want to contribute with these examples, you're welcome. Eventually I'll add them myself, but contributions are preferred.

**Comment by localleon** [comment]
Okay, i will prepare a pull request
