### ISSUE TITLE
Implementation of Beep with GLHF gets stuck during sound

### ISSUE THREAD

**Issue by MichaelMeir** [faiface/beep#22]
Ive tried using Beep to play sounds aswell as rendering images with GLHF but i cant seem to get it working.

Once the sound starts playing the images stop rendering as its on the same thread, ive tried using
`mainthread.Run(Sound.PlaySound)`
and
`mainthread.CallNonBlock(Sound.PlaySound)`
But both wont work to make audio and video work together
If im doing this totally wrong please tell me

**Comment by faiface** [comment]
You only have to run GLHF on the main thread, Beep is fine on any thread. Your problem is that you're running both graphics and sound on the main thread, but main thread can only do one thing at a time. Just call the Beep functions without any notion of the main thread and it'll all be fine.
