### ISSUE TITLE
Missing Documentation for Effects

### ISSUE THREAD

**Issue by localleon** [faiface/beep#24]
Hello, i am trying to use some effects on my Stream but i am unable to find documentation about the effects aspect of this libary. Could you provide me with a basic use case ? Im currently writing more examples for this libary ( #23 ). Im unable to find more infos in the godoc

**Comment by faiface** [comment]
All effects in the `effects` package are used in a manner very similar to the usage of `beep.Ctrl`, which is documented here: https://godoc.org/github.com/faiface/beep#Ctrl . Let me know if this helps, or not, if not I'll answer more thoroughly.

**Comment by localleon** [comment]
Thanks, i will look intonit
