### ISSUE TITLE
mp3: mp3: only layer3 (want 1; got 3) is supported!

### ISSUE THREAD

**Issue by wallnutkraken** [faiface/beep#3]
at `mp3.Decode()` caused by this file: http://www.podtrac.com/pts/redirect.mp3/traffic.libsyn.com/cortex/Cortex_053.mp3

Other MP3 files work fine.

**Comment by faiface** [comment]
This is a problem in https://github.com/hajimehoshi/go-mp3 . I can't estimate when this will be fixed, because the code for the MP3 decoder is ported over from a C++ implementation and we don't understand it :D (not that we attempted to).

**Comment by hajimehoshi** [comment]
I hope this has been already fixed: https://github.com/hajimehoshi/go-mp3/issues/9

**Comment by faiface** [comment]
Seems fixed, thanks a lot! I'm closing this, if it doesn't work for you @wallnutkraken, please reopen.
