### ISSUE TITLE
Run beep/examples/playing didn't hear the beep

### ISSUE THREAD

**Issue by Sombody1** [faiface/beep#32]
platform:mac os x 10.12.6

if i put this in the end ,it works:
time.Sleep(time.Millisecond*100)

it seems like if the sound was too short , like a beep,the seq streamer returned before the sound actually been played.

Did someone else have the same problem?

**Comment by faiface** [comment]
What's possibly happening is that because the size of the speaker buffer in the example is 1/10s, the audio is delayed roughly by 1/10s. Therefore, yeah, it may end up unplayed, which is fixed exactly by sleeping a bit.
