### ISSUE TITLE
two different audio streams at the same time?

### ISSUE THREAD

**Issue by FM1337** [faiface/beep#43]
Okay, so I know mixers are a thing in this library but what I need to do doesn't appear to be covered by that.

So let's say I have a game with background music playing, but I want to do sound effects when something happens, but I don't want the music to be interrupted/restarted and I want it to continue playing but also play the sound effect when it's needed

how would I go about accomplishing this?

**Comment by faiface** [comment]
Hi, all of this can be done in Beep, I'll be happy to help! But to avoid wasting time, tell me what you can do and where you're stumbling and I'll explain it from there.

**Comment by faiface** [comment]
I believe the mistake you are making is that you're calling `speaker.Init` each time you start playing something. That will reset the speaker. You should only call `speaker.Init` once at the beginning of your program.

**Comment by FM1337** [comment]
Hmm okay, I'll try only calling it once; but wouldn't that mean if you tried to play two different kinds of audio files, one is a .wav and the other is .mp3 wouldn't the sound be messed up because both of them would have a different sample rate?

**Comment by faiface** [comment]
Yes, they would, but that's what you should use `beep.Resample` for.

**Comment by FM1337** [comment]
Alright I appear to have it working, now I just need to find a way to lower the volume of the background music so I can hear some of the sound effects.

**Comment by faiface** [comment]
You can use the volume effect for that ;)

**Comment by marinat** [comment]
@FM1337 please, show example how did you do that :)

**Comment by FM1337** [comment]
I got it mostly working but it would segment on itself after the music was finished playing. I haven't touched the code in a few months but I'll look into it when I get time.

**Comment by marinat** [comment]
Your game was for mobile devices?
