### ISSUE TITLE
Ctrl and Loop

### ISSUE THREAD

**Issue by Lynges** [faiface/beep#46]
I am trying to pause a stream playing through beep.Loop, but when I attempt my program hangs. I am also using termui which makes it a little hard to debug.

Is this not supported?

I will post my code just in case I have messed something up. This is my first foray into go so it is quite possible that it is my fault.
```go
ctrl := &beep.Ctrl{Streamer: beep.Loop(1, stream)}

	// Init the Speaker with the SampleRate of the format and a buffer size of 1/10s
	speaker.Clear()
	speaker.Init(format.SampleRate, format.SampleRate.N(time.Second/10))

	// Internal channel, which will signal the end of the playback.
	internalPlay := make(chan struct{})

	speaker.Play(beep.Seq(ctrl, beep.Callback(func() {
		close(internalPlay)
	})))
```

And then later:
```go
		case stm := <-playControl:
			switch stm {
			case "pause":
				speaker.Lock()
				if ctrl.Paused {
					ctrl.Paused = false
				} else {
					ctrl.Paused = true
				}
				speaker.Unlock()
```

**Comment by faiface** [comment]
Hi, thanks for trying out Beep!

This should be entirely supported. You either made some mistake, or you've discovered a bug in Beep. The code you posted looks fine, so the problem must be somewhere else.

When exactly does the program hang? What gets executed and what doesn't? (a debugger, or just some print statements can help out)

**Comment by Lynges** [comment]
It behaves very odd. The first pause works, but subsequent does not and starting playback of another file also seems to affect it.
It is hard to explain, if you want to try for yourself the commit https://github.com/Lynges/susimup/commit/7ab71af302658eef8fd4a09c90e489910b2ec38e shows this behavior and contains both sample sound files to test with and a setup for logging to the `info.log` file in the repo.

**Comment by faiface** [comment]
Okay, I looked at your code and noticed 2 things that may be causing your problems:

1. You have two places in you `select` statement where you receive from the `playControl` channel:
```go
		case stm := <-playControl:
			switch stm {
			case "pause":
				// ...
		case <-playControl:
			break loop
}
```
The signal can only be received in one of them and which one it will be... well, that's random. That means, that in the 50% of the situations, the signal will be received in the second branch and the for loop will be terminated, meaning that no more signals will ever be received.

2. The other problem is that you have, and now after taking a second look at your code I'm not sure if I really know what the second problem is, but it's got something to do with channels. And maybe this will help you: when you send a value across a channel, the first goroutine that receives it will be the only goroutine to receive it. The value is not broadcasted to all goroutines having access to that channel.

**Comment by Lynges** [comment]
You are correct. I found a way to see logging from the program while running which allowed me to debug. And I found exactly what you also found. I also found an edge case when pressing pause before starting any player and everything seem to be working now. After all it was a bug in my code :) Thank you for your time and for bleep, it has made my project much easier.

**Comment by faiface** [comment]
Beep, not Bleep :P

I'm happy you made it work.

If you want to add more features to your player, Beep has some things. For example, you can use Resampler to change the playback speed, but with much higher quality than say on Youtube, and I can tell you, playing a song slowed down is freaking dope. Also, there are a few more things in the `effects` package.

**Comment by Lynges** [comment]
yeah, beep. Brainfart :P

Thanks for the suggestions, I will take a look and yes close this. Thank you again for your time.
