### ISSUE TITLE
Does beep work with gomobile for android?

### ISSUE THREAD

**Issue by udhos** [faiface/beep#5]
Can beep be used with gomobile to add sound into a native, pure Golang app for Android?

**Comment by faiface** [comment]
Yes, beep should work on Android (I haven't tested myself tho). Beep uses https://github.com/hajimehoshi/oto for the playback implementation in the `speaker` package and https://github.com/hajimehoshi/oto works on Android.

**Comment by udhos** [comment]
Thanks, will test it soon and report findings here.

**Comment by faiface** [comment]
Thanks, that will be appreciated, looking forward to how it goes!

**Comment by faiface** [comment]
Any news? If not, I'll close this.

**Comment by udhos** [comment]
Closing, will reopen in case of news.

**Comment by udhos** [comment]
Just to let you know beep works on Android with gomobile tool.

I am currently testing with this code:

```
func playLaser(game *gameState) {
	game.streamLaser.Seek(0)
	speaker.Play(beep.Seq(game.streamLaser))
}
```

https://github.com/udhos/fugo/blob/master/demo/invader/main.go
