### ISSUE TITLE
Struggling with Ctrl

### ISSUE THREAD

**Issue by Happy-Ferret** [faiface/beep#54]
I'm sure I'm doing something wrong, but I'd appreciate some help with the code below.

Basically, no matter what I do. ``Ctrl`` doesn't pause nor set the volume of the streamer.
Furthermore, the audio is not resampled to the file's sampling rate and thus stuck at ``44100``

```go
type Audio struct {
	filename string
	streamer beep.StreamSeekCloser
	format   beep.SampleRate
}

var monkey Audio

func init() {
	sr := beep.SampleRate(44100)
	speaker.Init(sr, sr.N(time.Second/10))
}

func main() {
	monkey.filename = "monkey.mp3"
	monkey.startMusic()
	monkey.test()
}

func (a *Audio) startMusic() {
	f, err := os.Open(a.filename)
	if err != nil {
		log.Fatal(err)
	}

	streamer, format, err := mp3.Decode(f)
	if err != nil {
		log.Fatal(err)
	}

	sr := format.SampleRate * 2

	resampled := beep.Resample(4, format.SampleRate, sr, streamer)

	speaker.Play(resampled)
	a.streamer = streamer
	a.format = sr
}

func (a *Audio) test() {
	ctrl := &beep.Ctrl{Streamer: beep.Loop(-1, a.streamer), Paused: false}
	volume := &effects.Volume{
		Streamer: ctrl,
		Base:     2,
		Volume:   0,
		Silent:   false,
	}

	speaker.Lock()
	volume.Volume -= 1.5 // <-- this right here
	ctrl.Paused = !ctrl.Paused
	speaker.Unlock()

	for {
		fmt.Print("Press [ENTER] to pause/resume. ")
		fmt.Scanln()

		speaker.Lock()
		ctrl.Paused = !ctrl.Paused
		volume.Volume += 0.5
		speaker.Unlock()
	}
}
```

**Comment by faiface** [comment]
Hi! Yeah, you're misunderstanding one thing, but don't worry, I'll explain :)

So, a Streamer is like a machine that produces audio samples when we call its Stream method. Usually, we don't call it manually. When we play a Streamer through the speaker, the speaker starts periodically calling the Stream method and playing what it gets.

Now, the main misunderstand you have it that functions like beep.Resample or the beep.Ctrl streamer don't modify the streamer you put in. So if you create a Ctrl, but send the original Streamer to the speaker, then what you'll hear will be the original thing.

Here's what they do. When you create a Ctrl (or a Resampler), you're creating a new Streamer. This new Streamer gets data from the original Streamer, modifies them somehow and returns the modified data from its Stream method. To get this modification going, you need to play the new Streamer, not the old one.

So, here's what you do. You need to wrap your original Streamer in beep.Resample. Then wrap the result of that in a Ctrl and send the result of that to the speaker. This way, you'll create a pipeline that does all you need. It loads the data from a file, then resamples it and then decides whether to play it or not based on the Paused flag.

Hope this helps :)

**Comment by Happy-Ferret** [comment]
Ok. So, in essence, like this?

```go
type Audio struct {
	filename string
}

var monkey Audio

func main() {
	sr := beep.SampleRate(44100)
	speaker.Init(sr, sr.N(time.Second/10))
	monkey.filename = "monkey.mp3"
	stream := monkey.startMusic()
	control(stream)
}

func control(ctrl *beep.Ctrl) {
	for {
		fmt.Print("Press [ENTER] to pause/resume. ")
		fmt.Scanln()

		speaker.Lock()
		ctrl.Paused = !ctrl.Paused
		speaker.Unlock()
	}
}

func (a Audio) startMusic() (CTRL *beep.Ctrl) {
	f, err := os.Open(a.filename)
	if err != nil {
		log.Fatal(err)
	}

	streamer, _, err := mp3.Decode(f)
	if err != nil {
		log.Fatal(err)
	}

	ctrl := &beep.Ctrl{Streamer: beep.Loop(-1, streamer), Paused: false}
	speaker.Play(ctrl)

	return ctrl
}
```

I don't suppose there's a way to do this via the struct as opposed to a return function?

I still have a thing or two to learn about Go, it appears.

PS: In case you're wondering what I need this for.
I'm in the process of writing my own little text adventure engine. All the sounds will be stored in a map of type ``map[*Audio]*Audio``, inside and initalized like so

```go
game.Sounds = map[*Audio]*Audio{
	&monkey: {
		filename: "monkey.mp3",
	},
	&loom: {
		filename: "loom.mp3",
	},
}
```

I should then be able to control sounds via things like:
```go
game.Sounds[&monkey].StartMusic()
player.Sounds[&monkey].Pause()
player.Sounds[&monkey].Seek(secs float64)
```
etc

**Comment by faiface** [comment]
Yeah, you got it right! :)

Btw, perhaps you know, but just to make sure. If your sound files aren't too big and you need to play them frequently, you may consider loading them into memory and playing them from there using a Buffer. You can learn about it [in this part of the tutorial](https://github.com/faiface/beep/wiki/To-buffer,-or-not-to-buffer,-that-is-the-question).

**Comment by faiface** [comment]
Oh, and your text adventure game with audio sounds great! Feel free to share it here when you get it working!

**Comment by Happy-Ferret** [comment]
NVM on that last question:

Assigning to a struct field actually works, too. I accidentally passed a copy instead of a pointer. Doh!

```go
type Audio struct {
	filename   string
	controller *beep.Ctrl
}

var monkey Audio

func main() {
	sr := beep.SampleRate(44100)
	speaker.Init(sr, sr.N(time.Second/10))
	monkey.filename = "monkey.mp3"
	monkey.startMusic()
	monkey.control()
}

func (a *Audio) control() {
	for {
		fmt.Print("Press [ENTER] to pause/resume. ")
		fmt.Scanln()

		speaker.Lock()
		a.controller.Paused = !a.controller.Paused
		speaker.Unlock()
	}
}

func (a *Audio) startMusic() {
	f, err := os.Open(a.filename)
	if err != nil {
		log.Fatal(err)
	}

	streamer, _, err := mp3.Decode(f)
	if err != nil {
		log.Fatal(err)
	}

	ctrl := &beep.Ctrl{Streamer: beep.Loop(-1, streamer), Paused: false}
	speaker.Play(ctrl)

	a.controller = ctrl
}
```

**Comment by Happy-Ferret** [comment]
Absolutely.
I'm going to release the engine under BSD3, once it's ready.

I'm kind of obsessed with everything iMuse/SCUMM, lately. With the audio part of my engine I'm hoping to take cues from iMuse's dynamic audio.

With your library that seems super easy. I can simply run a function at specified points of an audio stream, thus syncing audio to the overall game loop.

```go
func (a *Audio) onTime(timeEx float64, b func(), endOld bool) {
	for {
		select {
		case <-time.After(time.Second):
			runtime := a.format.D(a.streamer.Position()).Round(time.Second).Seconds()
			// fmt.Println(runtime)
			if runtime == timeEx {
				doOnce.Do(func() {
					b()
					if endOld {
						// Slowly fade out original audio track
					}
				})
			}
		}
	}
}
```

**Comment by faiface** [comment]
Yeah, you can also do it more precisely with the [Callback](https://godoc.org/github.com/faiface/beep#Callback) streamer. You can [Seq](https://godoc.org/github.com/faiface/beep#Seq) it after the right amount of [Silence](https://godoc.org/github.com/faiface/beep#Silence) and thus have a streamer than simply calls a function at a certain point in time. Then you can [Mix](https://godoc.org/github.com/faiface/beep#Mix) that with your track and you're good to go ;)

**Comment by faiface** [comment]
Can we close this issue? :)

**Comment by Happy-Ferret** [comment]
Oh. Sure. Sorry about that. :cat:

**Comment by faiface** [comment]
No problem.
