### ISSUE TITLE
Buffer.Pop pops n bytes instead of n samples

### ISSUE THREAD

**Issue by MarkKremer** [faiface/beep#63]
The documentation for `Buffer.Pop` states:

> Pop removes n samples from the beginning of the Buffer.

But this isn't the case. In my [test](https://play.golang.org/p/J5a12FwK1wD) it only pops half the number of samples.

This is the current source:
```golang
// Buffer is a storage for audio data. You can think of it as a bytes.Buffer for audio samples.
type Buffer struct {
	f    Format
	data []byte
	tmp  []byte
}

// ...

// Pop removes n samples from the beginning of the Buffer.
//
// Existing Streamers are not affected.
func (b *Buffer) Pop(n int) {
	b.data = b.data[n:]
}
```

`b.data` is of type `[]byte` but `Pop` doesn't take the sample length into account (1 sample has a width of 2 bytes in my test). I think it should be implemented something like this instead:
```golang
func (b *Buffer) Pop(n int) {
	b.data = b.data[n*b.f.Width():]
}
```

**Comment by faiface** [comment]
Hi, thanks for spotting this! I guess I should learn my lesson and unit test things thoroughly ;)

I’m currently on vacation, but feel free to make a PR to fix this.

**Comment by faiface** [comment]
Fixed in #64

**Comment by faiface** [comment]
Btw, a question. Do you use Pop for anything, or did you find the bug just by looking at the code? I’m asking because I thought Pop was useless :D

**Comment by MarkKremer** [comment]
I did use it to create overlapping windows. Something like this:
```golang
b := beep.NewBuffer(format)
chunk := beep.Take(chunkLen, streamer)
b.Append(chunk)

for {
    chunk = beep.Take(hopLen, streamer)
    b.Append(chunk)
    b.Pop(hopLen)
    // chunk has a length of chunkLen again but with the latest part of streamer.

    // do something with chunk.
}
```
I needed overlapping windows to
- Create better spectrograms (although I'm dropping that for now because I don't really need it and it's a hassle to program)
- Pass the last 2 seconds of microphone audio into a machine learning model every 1/4th of a second.

[My implementation of a microphone stream](https://github.com/MarkKremer/microphone) doesn't implement the seek method for obvious reasons, so that's why the buffer is useful.

But having looked at the source I don't think Buffer is the best solution for this because it converts everything to bytes and back while I only use the samples as floats. I may or may not handroll my own simplified buffer that just stores floats when I need the microphone thing again.

Enjoy your vacation!

**Comment by faiface** [comment]
Oh, right, I think I added the Pop method for something like this (a continuously updated buffer of bounded length), but I forgot since.

The buffer encodes samples into bytes to minimize memory usage in case of large buffers. Of course, it could (although I would measure it) slow down your program.

Btw, your microphone package is really cool, I checked it out ;)
