### ISSUE TITLE
Flac format requires mewkiz/flac

### ISSUE THREAD

**Issue by SolarLune** [faiface/beep#65]
Hey, it seems that flac support requires `go get github.com/mewkiz/flac`, but that's not mentioned in the dependencies / requirements.

**Comment by mewmew** [comment]
Hi @SolarLune,

The dependency on `mewkiz/flac` is mentioned in the go.mod file, which should be considered the source of truth regarding dependencies since documentation may become stale.

From https://github.com/faiface/beep/blob/76df4462a36ade5a7f7602277567319dfd398937/go.mod#L9:

```
module github.com/faiface/beep

require (
	github.com/gdamore/tcell v1.1.1
	github.com/hajimehoshi/go-mp3 v0.1.1
	github.com/hajimehoshi/oto v0.3.1
	github.com/jfreymuth/oggvorbis v1.0.0
	github.com/jfreymuth/vorbis v1.0.0 // indirect
	github.com/mewkiz/flac v1.0.5
	github.com/pkg/errors v0.8.1
)
```

**Comment by SolarLune** [comment]
Ah, I think I must have been using the old GOPATH approach, so `go get` didn't automatically download the requirements. I see; sorry about that. Thanks for the information!
