### ISSUE TITLE
Gain type doesn't implements Streamer interface

### ISSUE THREAD

**Issue by DmitriiTrifonov** [faiface/beep#91]
// Stream streams the wrapped Streamer amplified by Gain.
func (g *Gain) Stream(samples [][2]float64) (n int, ok bool) {
	n, ok = g.Streamer.Stream(samples)
	for i := range samples[:n] {
		samples[i][0] *= 1 + g.Gain
		samples[i][1] *= 1 + g.Gain
	}
	return n, ok
}

// Err propagates the wrapped Streamer's errors.
func (g *Gain) Err() error {
	return g.Streamer.Err()
}

To implement the Streamer interface the receiver should be not a pointer.

**Comment by faiface** [comment]
The `*Gain` type does implement `beep.Streamer`. Can you show me minimal code which causes problems for you?

**Comment by DmitriiTrifonov** [comment]
```func main() {
	f, err := os.Open("Example.ogg")
	if err != nil {
		log.Fatal(err)
	}
	streamer, format, err := vorbis.Decode(f)
	if err != nil {
		log.Fatal(err)
	}
	defer streamer.Close()
	gain := effects.Gain{Streamer: streamer, Gain: 1000}

	speaker.Init(format.SampleRate, format.SampleRate.N(time.Second/10))

	speaker.Play(gain)
	select{}
```

I've got an error: ./main.go:26:14: cannot use gain (type effects.Gain) as type beep.Streamer in argument to speaker.Play:
	effects.Gain does not implement beep.Streamer (Err method has pointer receiver)

Maybe I should use &gain instead of simply gain.

**Comment by faiface** [comment]
> Maybe I should use &gain instead of simply gain.

That’s right! In Go, `T` and `*T` are two different types and one can implement an interface and another one might not. When you look at the methods of `Gain`, they all accept `*Gain`, that’s why `*Gain` implements `beep.Streamer` (no `*` there, though and not `Gain`.

**Comment by DmitriiTrifonov** [comment]
Thanks for replying. I'm closing the issue!
