### ISSUE TITLE
Looping a Resampler

### ISSUE THREAD

**Issue by skuzzymiglet** [faiface/beep#92]
Sometimes you resample and then want to loop. It seems you can't use Resampler as a StreamSeeker. How should I approach this?

**Comment by faiface** [comment]
You have two choices:
1. First loop, then resample the looped streamer.
2. Resample, then use a Buffer to save the resampled content into a buffer (loop up [this tutorial](https://github.com/faiface/beep/wiki/To-buffer,-or-not-to-buffer,-that-is-the-question)). The Buffer then allows you to create a StreamSeeker of its content.

**Comment by skuzzymiglet** [comment]
It doesn't seem like Buffer implements StreamSeeker:

```
cannot use toTempo(buf, format, *tempo) (type beep.Resampler) as type beep.StreamSeeker in argument to beep.Loop: beep.Resampler does not implement beep.StreamSeeker (Err method has pointer receiver)
```

**Comment by MarkKremer** [comment]
Buffer has a `buffer.Streamer(0, buffer.Len())` method that does return one.

**Comment by skuzzymiglet** [comment]
Good stuff
